apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        env:
        - name: MONGO_HOST
          value: {{ .Values.backend.environment.MONGO_HOST }}
        - name: MONGO_PORT
          value: {{ .Values.backend.environment.MONGO_PORT }}
