apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
  - port: {{ .Values.frontend.servicePort }}
    targetPort: {{ .Values.frontend.containerPort }}
    nodePort: {{ .Values.frontend.nodePort }}
  selector:
    app: frontend
