apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.secret.username | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.secret.password | b64enc }}
